[package]
name = "sdl2-work"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
sdl2 = {version = "0.37.0", features = ["gfx", "ttf"]}
simple_logger = "5.0.0"
vector3 = "1.1.4"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
